### ISSUE TITLE
模板中写行内样式带color属性会引起模板出错

### ISSUE THREAD

**Issue by yshysh123** [joe-sky/nornj#17]
在升级nornj版本之后。在nj模板中写入如下代码：
```
nj`<table width="410" height="210" class="${styles.explainTable}">
              <tr>
                <td class="${styles.explainTableTd1}">A<br />AAA</td>
                <td class="${styles.explainTableTd2}">B<br />BBB</td>
              </tr>
              <tr>
                <td class="border-bottom: 1px dashed #ccc;">C<br />CCC</td>
                <td>D<br />DDD</td>
              </tr>
 </table>`()
```
控制台打印出错：
![我是图片](https://user-images.githubusercontent.com/29161483/44252854-44ba7380-a230-11e8-8b56-692dbb79e307.png)

目前的解决方案如下：
1、JS中nj模板尽量换成JSX语法
2、将行内style全部换成class

**Comment by joe-sky** [comment]
@yshysh123 这个是模板在解析`<br #show={false}>`语法时有未考虑到的场景引起的bug，已经修复：
* [ChangeLog](https://github.com/joe-sky/nornj/blob/master/CHANGELOG.md#v0411-20180817)
* [测试用例](https://github.com/joe-sky/nornj/blob/master/test/helpers/extensionAttribute.spec.js#L10)
