### ISSUE TITLE
作者您好，如下问题麻烦帮助解决下

### ISSUE THREAD

**Issue by pp-ball** [joe-sky/nornj#18]
![image](https://user-images.githubusercontent.com/30425837/45155662-4adbb880-b20e-11e8-9053-0059f547de95.png)
使用 npm run build-web-dev构建到后台后，后台访问如图。劳烦帮忙看看问题，感谢

**Comment by joe-sky** [comment]
这个`#set`是`Velocity`语法，[这个多页模板](https://github.com/joe-sky/nornj-cli/tree/master/templates/react-mobx)在构建后原html文件默认会生成vm文件，[这里配的](https://github.com/joe-sky/nornj-cli/blob/master/templates/react-mobx/configs.js#L26)。

这个得在支持`Velocity`的java服务端才能解析。

**Comment by chenlizhi8** [comment]
如果我想使用freeMarker,直接把configs.js中修改：
`indexExtName: '.ftl', `
就可以了吗？还需要修改其他地方吗？
试了一下，Java服务端生成了.ftl文件，但访问还是和之前页面还是和之前一样效果。

**Comment by joe-sky** [comment]
`NornJ-cli`中预置的`react-mobx`模板默认是使用`Velocity`，可以改成使用`freeMarker`。但是需要修改的地方比较多，至少有4-5处。这里有一个使用`freeMarker`的项目模板：[https://github.com/joe-sky/react-mobx-ftl](https://github.com/joe-sky/react-mobx-ftl)，可以用它重新初始化新项目。

使用[NornJ-cli的下载模板功能](https://github.com/joe-sky/nornj-cli#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF)可以直接使用这个模板：

1. 输入`nj init`
2. 选`other`，然后输入`joe-sky/react-mobx-ftl`就可以了

代码具体都改了哪里，您可以看下这个`freeMarker`模板的代码。另外，`configs.js`里默认配置的文件路径等未必完全适合您的后端java项目，如果不一致则需要修改。

**Comment by chenlizhi8** [comment]
![1536546176 1](https://user-images.githubusercontent.com/30425837/45273476-895ec500-b4e5-11e8-857b-00d65b49a462.png)
现在后台访问是这样的，感觉是不是有些文件没有打进来，后台返回了ftl文件内容，但浏览器没有渲染

**Comment by chenlizhi8** [comment]
不知道为什么使用layout/default.html不生效，将它的内容直接写在index.html中就可以了，
![image](https://user-images.githubusercontent.com/30425837/45281497-98a43980-b50a-11e8-9911-8f9da62b8d79.png)
目前已经好使了，感谢您的耐心指导，谢谢
