### ISSUE TITLE
babel-plugin-nornj-in-jsx在tsx中不生效？

### ISSUE THREAD

**Issue by wittech** [joe-sky/nornj#33]
babel-plugin-nornj-in-jsx在tsx中不生效？

**Comment by joe-sky** [comment]
能支持TSX，但只限使用babel v7+的项目；使用ts-loader的项目不支持，因为babel-plugin-nornj-in-jsx是babel插件，只支持babel解析ts时转换，没有为原生的tsc提供转换功能。

用create-react-app建的项目就可以支持的，这有个demo。babel配置在这里：
https://github.com/joe-sky/nornj-antd-v4-demo/blob/master/package.json#L165

在TSX中使用的例子：
https://github.com/joe-sky/nornj-antd-v4-demo/blob/master/src/AppLink.tsx

**Comment by wittech** [comment]
好的感谢！
