### ISSUE TITLE
Why are there few people supporting

### ISSUE THREAD

**Issue by yakiler** [joe-sky/nornj#37]
When I first saw the tool, it felt like it was basically complete, with some basic documentation and some appeal (operator expansion, etc.), but why not many users? Is it because React's design principles jsx don't expect too many complicated usages? If possible, are there more users?

**Comment by joe-sky** [comment]
Sorry, I'm too busy recently, so my reply is late 😂. My answer to the question is as follows:

1. This project has not been known by many people. The latest version has just been completed. I didn't do any promotion before it was finished. I'll try to push it out soon to see if it can get more users.

2. JSX extension is a very minority field. Most JSX extension project only use Babel to make the grammar sugar, and few projects are well done, but there are exceptions like this: https://github.com/AlexGilleran/jsx-control-statements. Speaking of React's design principles, it seems that it has not been explicitly mentioned that JSX extensions are not allowed, but there are certainly many people who do not want to change their habits of React development. For example, when JSX first came out in 2013, many people did not adapt to it.

3. The NornJ latest version will try to conform to the style of React environment, but it is not an official Facebook project, it's a community developer project. It has its own features, merits. I want to start from the extensibility, strive to achieve different JSX. This has been a lot of practice in our company's projects, and I will gradually make it public.

**Comment by yakiler** [comment]
I hope it will be better and better, come on
