### ISSUE TITLE
是否支持嵌套的数据格式？

### ISSUE THREAD

**Issue by Great-old-one** [joe-sky/nornj#42]
例如，数据结构如下

```json
{
  "goods": {
    "price": 1
  },
  "activity": {
    "start_time": "2020-01-20"
  }
}
```

formData定义

```js
formData = (<mobxFormData>
  <mobxFieldData name="goods.price" type="number"/>
  <mobxFieldData name="activity.start_time"/>
</mobxFormData>).formData

```

form中使用

```js
<Form>
  <FormItem label="商品价格" mobxField={formData["goods.price"]}>
    <Input/>
  </FormItem>
  <FormItem label="活动开始时间" mobxField={formData["activity.start_time"]}>
    <Input/>
  </FormItem>
</Form>

```

在使用过程中发现这个功能还是挺有必要，但是在文档中没有看到相关的介绍。如果未支持，是否考虑在以后的版本中添加该功能？

**Comment by joe-sky** [comment]
@Great-old-one 上述的这个场景目前也能支持，这样写：

```js

const data {
  "goods": {
    "price": 1
  },
  "activity": {
    "start_time": "2020-01-20"
  }
};

@observer
class TestForm extends React.Component {
  @observable formData = (
    <mobxFormData>
      <mobxFieldData name="goods.price" value={data.goods.price} type="number" />
      <mobxFieldData name="activity.start_time" value={data.activity.start_time} />
    </mobxFormData>
  ).formData;

  render() {
    return (
      <Form>
        <FormItem label="商品价格" mobxField={`formData['goods.price']`}>
          <Input/>
        </FormItem>
        <FormItem label="活动开始时间" mobxField={`formData['activity.start_time']`}>
          <Input/>
        </FormItem>
      </Form>
    );
  }
}
```

这种写法就是处理要用动态表达式从 formData 实例中取数据的问题，文档在[点这个链接里](https://joe-sky.gitee.io/nornj/mobx-extension/mobx-form-data#mobxfield)提到过：

```js
//mobxField 也可以支持绑定动态数据，语法稍有不同：

<Each of={users}>
  <Form.Item mobxField={`formData[item.userName]`} label={item.userName}>
    <Input />
  </Form.Item>
</Each>
```

但上述方式似乎不够优雅，想了下我会考虑未来加一个直接给mobxFormData标签传多层数据初始值的方式，比如：

```js
<mobxFormData fields={{
  "goods": {
    "price": 1
  },
  "activity": {
    "start_time": "2020-01-20"
  }
}}>
  <mobxFieldData name="goods.price" type="number" />
  <mobxFieldData name="activity.start_time" />
</mobxFormData>
```

当然只是初步想法，还要再继续优化思路 😅

**Comment by Great-old-one** [comment]
> @Great-old-one 仔细想了下，上述的这个场景目前也能支持，这样写：
> 
> ```js
> import flatten from 'flat';
> 
> const data {
>   "goods": {
>     "price": 1
>   },
>   "activity": {
>     "start_time": "2020-01-20"
>   }
> };
> 
> @observer
> class TestForm extends React.Component {
>   @observable formData = (
>     <mobxFormData>
>       <mobxFieldData name="goods.price" type="number" />
>       <mobxFieldData name="activity.start_time" />
>     </mobxFormData>
>   ).formData;
> 
>   componentDidMount() {
>     this.formData.setValue(flatten(data));
>   }
> 
>   render() {
>     return (
>       <Form>
>         <FormItem label="商品价格" mobxField={`formData['goods.price']`}>
>           <Input/>
>         </FormItem>
>         <FormItem label="活动开始时间" mobxField={`formData['activity.start_time']`}>
>           <Input/>
>         </FormItem>
>       </Form>
>     );
>   }
> }
> ```
> 
> 不过这样就是要把对象展平成一层，因为这个基于mobx的formData数据目前就设计只能支持一层可观察数据。
> 
> 还有就是
> 
> ```js
> mobxField={`formData['xxx.xxx']`}
> ```
> 
> 这种写法是处理要用动态表达式从 formData 实例中取数据的问题，文档在[点这个链接里](https://joe-sky.gitee.io/nornj/mobx-extension/mobx-form-data#mobxfield)提到过：
> 
> ```js
> //mobxField 也可以支持绑定动态数据，语法稍有不同：
> 
> <Each of={users}>
>   <Form.Item mobxField={`formData[item.userName]`} label={item.userName}>
>     <Input />
>   </Form.Item>
> </Each>
> ```

我们的业务中每个对象中会有重复的key，这种把对象展开的形式可能会引起一些问题，后来我使用了另外一种形式。

formData定义:
```js
@observable
priceFormData = (
  <mobxFormData>
    <mobxFieldData name="price" type="number" min={1} max={100}/>
  </mobxFormData>
).formData

@observable
formData = (
  <mobxFormData>
    <mobxFieldData name="goods" type="object" value={this.priceFormData}/>
  </mobxFormData>
).formData;

```

使用数据绑定
```js
<Form>
  <FormItem label="商品价格" mobxField={this.formData.goods.price}>
    <Input/>
  </FormItem>
</Form>
```

**Comment by joe-sky** [comment]
呃，这个方法我确实也没想到，不过感觉从mobxFormData标签和mobxField指令的实现上看确实是可行的😮。

只不过有个问题要注意下，就是像上面这样写的话，调`formData.validate()`进行校验时，不会触发`this.formData.goods`这一层的数据校验。不过貌似再单独调一次`this.formData.goods.validate()`或`priceFormData.validate()`进行校验应该就行了。
