### ISSUE TITLE
独立模板文件中分模块构建 通过webpack 的形式

### ISSUE THREAD

**Issue by devmsg** [joe-sky/nornj#7]
![image](https://user-images.githubusercontent.com/15261658/30092449-984e07fe-92f1-11e7-9c9e-5b44b8ddb4b4.png)

打印出来的是字符串的html  并不能直接渲染出来真正的div标签  
直接编译并直接输出react组件是可以呗渲染成dom标签的！

![image](https://user-images.githubusercontent.com/15261658/30092653-e059e9d6-92f2-11e7-8d8b-b3410c58a2e9.png)

![image](https://user-images.githubusercontent.com/15261658/30092668-e611dfbe-92f2-11e7-95d6-d5404df47235.png)

怎么解决呢？是修改loader吗？

**Comment by devmsg** [comment]
目前解决办法是通过nj将html字符串渲染出去  不知道这样做是否规范
![Uploading image.png…]()

**Comment by devmsg** [comment]
定义的nj模板之后 如何在模板里定义样式呢？只能通过props嘛?

**Comment by joe-sky** [comment]
`nj`模板接上`React`后是用来渲染`vdom`的，而无需用`dangerouslySetInnerHTML`，上面那个状况应该是有些东西没配置对，应主要是以下两个原因：

1. `nornj-loader`的配置不对，少个参数：
```js
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['babel-loader'], exclude: /node_modules/ },
      {
        test: /\.nj.html(\?[\s\S]+)*$/,
        loader: 'nornj',
        query: {
          outputH: true,
          delimiters: 'react'  //这个要加
        }
      }
    ]
  }
```

2. `nornj-react`包至少得引一下，因为这个模板默认配置是渲染`html`字符串的，而且插值参数语法是双花括号，即`{{a}}`；引这个包后，模板默认配置会改为渲染`React vdom`对象，且插值参数语法改为单花括号，即`{a}`。所以和`React`一起用时是单花括号，和`JSX`一样。

具体你可以跑跑这个`Redux`的例子，我更新依赖到了最新的`nj`：[地址点这里](https://github.com/joe-sky/nornj/tree/master/examples/react-redux-nornj-todomvc)。下载安装依赖后，运行下`webpack`命令，然后浏览器打开`index.html`就可以运行了。

样式我们一般使用`css modules`或`styled components`来配合`nj`使用，`nj`模板里可以直接这样写style：`style="margin:10px;"`，不必非像`JSX`那样写成对象。

其实这个模板做了很久已不是个玩具了，在我们公司内部已经大面积使用了，各种场景应用基本都有覆盖，离正式开源应不远了，到时我把没写好的实例文档都会补上，如有问题可以随时找我:smile:

**Comment by devmsg** [comment]
@joe-sky webpack 没有加上options的参数，不过谢谢啦，就想要个这种模板引擎！！😄
